<a href="https://colab.research.google.com/github/GokulnathMsd/PROJECT/blob/main/Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Installing and Importing the required Python Packages and Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
%matplotlib inline
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import svm
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [ ]:
pip install category_encoders

     |████████████████████████████████| 82 kB 401 kB/s 


**Mounting the Google Drive**

In [ ]:
# Mount the Google Drive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


**Read the Data file and check**

In [ ]:
df = pd.read_csv('gdrive/My Drive/Heart-Disease-Project/Data-Files/Heart-Disease-Data.csv')
print(df.shape)
df.head()

(573, 15)


patient_id  age  sex  cp  trestbps  ...  oldpeak  slope  ca  thal  target
0           1   63    1   3       145  ...      2.3      0   0     1       1
1           2   37    1   2       130  ...      3.5      0   0     2       1
2           3   41    0   1       130  ...      1.4      2   0     2       1
3           4   56    1   1       120  ...      0.8      2   0     2       1
4           5   57    0   0       120  ...      0.6      2   0     2       1

[5 rows x 15 columns]

**Execute the "info()" command and check datatypes of the Columns and Missing Data**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   patient_id  573 non-null    int64  
 1   age         573 non-null    int64  
 2   sex         573 non-null    int64  
 3   cp          573 non-null    int64  
 4   trestbps    573 non-null    int64  
 5   chol        573 non-null    int64  
 6   fbs         573 non-null    int64  
 7   restecg     573 non-null    int64  
 8   thalach     573 non-null    int64  
 9   exang       573 non-null    int64  
 10  oldpeak     573 non-null    float64
 11  slope       573 non-null    int64  
 12  ca          573 non-null    int64  
 13  thal        573 non-null    int64  
 14  target      573 non-null    int64  
dtypes: float64(1), int64(14)
memory usage: 67.3 KB


**Summarize the columnwise Missing Data**

In [ ]:
df.isnull().sum()

patient_id    0
age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
slope         0
ca            0
thal          0
target        0
dtype: int64

In [ ]:
df.shape

(573, 15)

In [ ]:
print(df.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...  
568    False
569    False
570    False
571    False
572    False
Length: 573, dtype: bool


In [ ]:
df.drop_duplicates(inplace = True)

In [ ]:
df.shape

(573, 15)

In [ ]:
df['target'].value_counts()

0    288
1    285
Name: target, dtype: int64

**Slice X and y Values**

In [ ]:
X = df.drop(['target'], axis = 1)
y = df['target']
X.head()

patient_id  age  sex  cp  trestbps  ...  exang  oldpeak  slope  ca  thal
0           1   63    1   3       145  ...      0      2.3      0   0     1
1           2   37    1   2       130  ...      0      3.5      0   0     2
2           3   41    0   1       130  ...      0      1.4      2   0     2
3           4   56    1   1       120  ...      0      0.8      2   0     2
4           5   57    0   0       120  ...      1      0.6      2   0     2

[5 rows x 14 columns]

In [ ]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

**Execute Train-Test-Split Command and Verify**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 66)

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(458, 14)
(458,)
(115, 14)
(115,)


**Learn the Data and Predict the dependent Variable values for the "X_test"data using "LogisticRegression()" algorithm**

In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)

LogisticRegression()

**Calculate the Accuracy of the Model**

In [ ]:
accuracy_lr = logmodel.score(X_test, y_test)
print("Accuracy of Logistic Regression on test set:",accuracy_lr)

Accuracy of Logistic Regression on test set: 0.8


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix  
y_pred=logmodel.predict(X_test)
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[55 14]
 [ 9 37]]
              precision    recall  f1-score   support

           0       0.86      0.80      0.83        69
           1       0.73      0.80      0.76        46

    accuracy                           0.80       115
   macro avg       0.79      0.80      0.79       115
weighted avg       0.81      0.80      0.80       115



##**FEATURE SCALING**

**Normalization**

In [ ]:
df.columns

Index(['patient_id', 'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [ ]:
columnNames = ['patient_id', 'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']

In [ ]:
min_max_scaler_object = preprocessing.MinMaxScaler()
X_train1 = min_max_scaler_object.fit_transform(X_train)
X_train1 = pd.DataFrame(X_train1 , columns = columnNames)
X_train1.head()

patient_id       age  sex    cp  ...   oldpeak     slope    ca      thal
0    0.663158  0.208333  0.0  0.75  ...  0.000000  0.333333  0.00  0.428571
1    0.324561  0.520833  1.0  0.00  ...  0.354839  0.333333  0.25  0.428571
2    0.029825  0.833333  0.0  0.75  ...  0.290323  0.666667  0.50  0.285714
3    0.321053  0.312500  1.0  0.00  ...  0.000000  0.666667  0.25  0.285714
4    0.547368  0.500000  1.0  1.00  ...  0.000000  0.333333  0.00  1.000000

[5 rows x 14 columns]

In [ ]:
min_max_scaler_object = preprocessing.MinMaxScaler()
X_test1 = min_max_scaler_object.fit_transform(X_test)
X_test1 = pd.DataFrame(X_test1 , columns = columnNames)
X_test1.head()

patient_id       age  sex    cp  ...   oldpeak     slope        ca      thal
0    0.513181  0.690476  0.0  0.00  ...  0.451613  0.333333  0.666667  0.142857
1    0.534271  0.904762  0.0  0.75  ...  0.258065  0.666667  0.000000  1.000000
2    0.358524  0.785714  0.0  0.00  ...  1.000000  0.000000  1.000000  0.428571
3    0.495606  0.714286  1.0  0.50  ...  0.354839  0.333333  0.333333  0.142857
4    0.637961  0.666667  1.0  0.75  ...  0.032258  0.333333  0.333333  1.000000

[5 rows x 14 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel1 = LogisticRegression()
logmodel1.fit(X_train1, y_train)

LogisticRegression()

In [ ]:
#predictions
predictions1 = logmodel1.predict(X_test1)

In [ ]:
print(confusion_matrix(y_test, predictions1))
print(classification_report(y_test,predictions1))

[[55 14]
 [ 9 37]]
              precision    recall  f1-score   support

           0       0.86      0.80      0.83        69
           1       0.73      0.80      0.76        46

    accuracy                           0.80       115
   macro avg       0.79      0.80      0.79       115
weighted avg       0.81      0.80      0.80       115



**HERE,WE GET ACCURACY OF 80% SO WE USE DON'T NORMALIZATION**

##**DIMENSIONALITY REDUCTION**

**Applying PCA**

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X6_train = pca.fit_transform(X_train)
X6_test = pca.transform(X_test)
X6 = pca.transform(X)
print(X6_train.shape)
print(X6_test.shape)
print(X6_train[:5])
print(y[:5])

(458, 2)
(115, 2)
[[  97.03475302  -53.65241906]
 [ -93.08643381   20.66086138]
 [-262.09628398   -1.30073226]
 [ -95.38245763   43.03794484]
 [  33.11332753  -20.9550792 ]]
0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64


In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel = LogisticRegression()
logmodel.fit(X6_train, y_train)

LogisticRegression()

In [ ]:
#predictions
predictions6 = logmodel.predict(X6_test)

In [ ]:
print(confusion_matrix(y_test, predictions6))
print(classification_report(y_test,predictions6))

[[37 32]
 [19 27]]
              precision    recall  f1-score   support

           0       0.66      0.54      0.59        69
           1       0.46      0.59      0.51        46

    accuracy                           0.56       115
   macro avg       0.56      0.56      0.55       115
weighted avg       0.58      0.56      0.56       115



**Using LDA**

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)
X7_train = lda.fit_transform(X_train, y_train)
X7_test = lda.transform(X_test)
X7=lda.transform(X)
print(X7_train[:5])
print()
print(X7_test[:5])

[[-0.88228899]
 [-0.99504671]
 [ 3.01242614]
 [-0.49843781]
 [ 2.05959448]]

[[-2.76291407]
 [ 2.76944113]
 [-1.68542767]
 [-1.25330533]
 [ 0.09816301]]


In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel = LogisticRegression()
logmodel.fit(X7_train, y_train)

LogisticRegression()

In [ ]:
#predictions
predictions7 = logmodel.predict(X7_test)

In [ ]:
print(confusion_matrix(y_test, predictions7))
print(classification_report(y_test,predictions7))

[[55 14]
 [ 9 37]]
              precision    recall  f1-score   support

           0       0.86      0.80      0.83        69
           1       0.73      0.80      0.76        46

    accuracy                           0.80       115
   macro avg       0.79      0.80      0.79       115
weighted avg       0.81      0.80      0.80       115



##**All Classifiers**

**Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression(random_state = 0)
lr_clf.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
lr_clf_Train_acc= lr_clf.score(X_train,y_train)
lr_clf_Test_acc= lr_clf.score(X_test,y_test)

In [ ]:
print('Accuracy on training set:',lr_clf_Train_acc)
print('Accuracy on test set:',lr_clf_Test_acc)

Accuracy on training set: 0.8253275109170306
Accuracy on test set: 0.8


In [ ]:
y_pred = lr_clf.predict(X_test)
y_pred

array([0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0])

In [ ]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[55 14]
 [ 9 37]]
              precision    recall  f1-score   support

           0       0.86      0.80      0.83        69
           1       0.73      0.80      0.76        46

    accuracy                           0.80       115
   macro avg       0.79      0.80      0.79       115
weighted avg       0.81      0.80      0.80       115



**Random Forest Classifier**

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf_clf = RandomForestRegressor(n_estimators = 10, random_state = 0)
rf_clf.fit(X_train,y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [ ]:
rf_clf_Train_acc = rf_clf.score(X_train,y_train)
rf_clf_Test_acc=rf_clf.score(X_test,y_test)

In [ ]:
print('Accuracy on training set:',rf_clf_Train_acc)
print('Accuracy on test set:',rf_clf_Test_acc)

Accuracy on training set: 0.9444355285531418
Accuracy on test set: 0.6822463768115943


In [ ]:
y_pred = rf_clf.predict(X_test)
y_pred

array([0. , 0.5, 0.1, 0. , 0.5, 0.9, 1. , 0. , 0.8, 0.1, 1. , 1. , 0.4,
       0. , 0.3, 1. , 0.1, 0.6, 0.2, 0. , 0.5, 0. , 1. , 0.6, 1. , 1. ,
       1. , 0.9, 0.8, 0.7, 0. , 0. , 1. , 0.4, 1. , 0.6, 0.4, 0.1, 1. ,
       0. , 0.3, 0.5, 1. , 0.8, 0. , 0. , 0. , 1. , 0. , 1. , 0.1, 0. ,
       0. , 0.1, 0.1, 0.5, 1. , 1. , 1. , 0. , 1. , 0. , 0. , 0.7, 0.4,
       0. , 0. , 1. , 0. , 0. , 0.8, 0. , 0. , 0. , 0. , 0.4, 0.6, 0. ,
       1. , 0.3, 1. , 0.3, 0. , 0. , 0.1, 0. , 0.4, 0.1, 0. , 0. , 0.8,
       0. , 1. , 0. , 0. , 1. , 1. , 1. , 0. , 0.2, 0. , 0. , 0. , 0. ,
       1. , 0. , 0.7, 0. , 1. , 0.8, 0.9, 0.9, 1. , 0. , 0.2])

In [ ]:
x=y_pred.astype(int)
print(x)

[0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0
 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0
 0 1 0 0]


In [ ]:
print(confusion_matrix(y_test,x))  
print(classification_report(y_test,x))  

[[69  0]
 [18 28]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88        69
           1       1.00      0.61      0.76        46

    accuracy                           0.84       115
   macro avg       0.90      0.80      0.82       115
weighted avg       0.88      0.84      0.83       115



**Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb_clf= GaussianNB()
nb_clf.fit(X_train,y_train)

GaussianNB()

In [ ]:
nb_clf_Train_acc=nb_clf.score(X_train,y_train)
nb_clf_Test_acc=nb_clf.score(X_test,y_test)

In [ ]:
print('Accuracy on training set:',nb_clf_Train_acc)
print('Accuracy on test set:',nb_clf_Test_acc)

Accuracy on training set: 0.8165938864628821
Accuracy on test set: 0.7913043478260869


In [ ]:
y_pred = nb_clf.predict(X_test)
y_pred

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0])

In [ ]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[55 14]
 [10 36]]
              precision    recall  f1-score   support

           0       0.85      0.80      0.82        69
           1       0.72      0.78      0.75        46

    accuracy                           0.79       115
   macro avg       0.78      0.79      0.79       115
weighted avg       0.80      0.79      0.79       115



**DecisionTree Classifier**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dec_clf = DecisionTreeClassifier()
dec_clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
dec_clf_Train_acc=dec_clf.score(X_train,y_train)
dec_clf_Test_acc=dec_clf.score(X_test,y_test)

In [ ]:
print('Accuracy on training set:', dec_clf_Train_acc)
print('Accuracy on test set:',dec_clf_Test_acc)

Accuracy on training set: 1.0
Accuracy on test set: 0.8956521739130435


In [ ]:
y_pred = dec_clf.predict(X_test)
y_pred

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0])

In [ ]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[61  8]
 [ 4 42]]
              precision    recall  f1-score   support

           0       0.94      0.88      0.91        69
           1       0.84      0.91      0.87        46

    accuracy                           0.90       115
   macro avg       0.89      0.90      0.89       115
weighted avg       0.90      0.90      0.90       115



**KNN Classifier**

In [ ]:
knn_clf = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)  
knn_clf.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
kNN_Train_acc=knn_clf.score(X_train,y_train)
kNN_Test_acc=knn_clf.score(X_test,y_test)

In [ ]:
print('Accuracy on training set:',kNN_Train_acc)
print('Accuracy on test set:',kNN_Test_acc)

Accuracy on training set: 0.8820960698689956
Accuracy on test set: 0.808695652173913


In [ ]:
y_pred = knn_clf.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0])

In [ ]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[57 12]
 [10 36]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84        69
           1       0.75      0.78      0.77        46

    accuracy                           0.81       115
   macro avg       0.80      0.80      0.80       115
weighted avg       0.81      0.81      0.81       115



**Support Vector Classifier**

In [ ]:
from sklearn.svm import SVC
kernel_svm_clf = SVC(kernel = 'rbf', random_state = 0)
kernel_svm_clf.fit(X_train, y_train)

SVC(random_state=0)

In [ ]:
kernal_SVM_Train_acc=kernel_svm_clf.score(X_train,y_train)
kernal_SVM_Test_acc=kernel_svm_clf.score(X_test,y_test)

In [ ]:
print('Accuracy on training set:',kernal_SVM_Train_acc)
print('Accuracy on test set:',kernal_SVM_Test_acc)

Accuracy on training set: 0.8013100436681223
Accuracy on test set: 0.782608695652174


In [ ]:
y_pred = kernel_svm_clf.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0])

In [ ]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[62  7]
 [18 28]]
              precision    recall  f1-score   support

           0       0.78      0.90      0.83        69
           1       0.80      0.61      0.69        46

    accuracy                           0.78       115
   macro avg       0.79      0.75      0.76       115
weighted avg       0.79      0.78      0.78       115



##**AdaBoost Classifier**

In [ ]:
model = DecisionTreeClassifier(criterion='entropy', max_depth=1)
AdaBoost = AdaBoostClassifier(base_estimator=model, n_estimators=100, learning_rate=1)

In [ ]:
#Fit the model with training data
boostmodel = AdaBoost.fit(X_train, y_train)

In [ ]:
#Evaluate the accuracy of the model
y_pred = boostmodel.predict(X_test1)
AdaBoost_acc = metrics.accuracy_score(y_test, y_pred)
#Calculating the accuracy in percentage
print('The accuracy is: ', AdaBoost_acc * 100, '%')

The accuracy is:  40.0 %


In [ ]:
AdaBoost_Train_acc= boostmodel.score(X_train1,y_train)
AdaBoost_Test_acc= boostmodel.score(X_test1,y_test)
print('Accuracy on training set:',AdaBoost_Train_acc)
print('Accuracy on test set:',AdaBoost_Test_acc)

Accuracy on training set: 0.5218340611353712
Accuracy on test set: 0.4


##**Gradient Boosting**

In [ ]:
lr_list = [0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1]

for learning_rate in lr_list:
    gb_clf = GradientBoostingClassifier(n_estimators=20, learning_rate=learning_rate, max_features=2, max_depth=2, random_state=0)
    gb_clf.fit(X_train1, y_train)

    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(gb_clf.score(X_train, y_train)))
    print("Accuracy score (validation): {0:.3f}".format(gb_clf.score(X_test, y_test)))

Learning rate:  0.05
Accuracy score (training): 0.528
Accuracy score (validation): 0.400
Learning rate:  0.075
Accuracy score (training): 0.526
Accuracy score (validation): 0.400
Learning rate:  0.1
Accuracy score (training): 0.526
Accuracy score (validation): 0.400
Learning rate:  0.25
Accuracy score (training): 0.522
Accuracy score (validation): 0.409
Learning rate:  0.5
Accuracy score (training): 0.611
Accuracy score (validation): 0.583
Learning rate:  0.75
Accuracy score (training): 0.531
Accuracy score (validation): 0.513
Learning rate:  1
Accuracy score (training): 0.598
Accuracy score (validation): 0.565


In [ ]:
from array import array
gb_clf2 = GradientBoostingClassifier(n_estimators=20, learning_rate=0.75, max_features=2, max_depth=2, random_state=0)
gb_clf2.fit(X_train1, y_train)
predictions = gb_clf2.predict(X_test1)
#GradientBoosting_acc=gb_clf2.score(Y_test, predictions)
GradientBoosting_acc = metrics.accuracy_score(y_test, predictions)
print("GradientBoosting_acc =", GradientBoosting_acc)

GradientBoosting_acc = 0.9130434782608695


In [ ]:
GradientBoost_Train_acc= gb_clf2.score(X_train1,y_train)
GradientBoost_Test_acc= gb_clf2.score(X_test1,y_test)
print('Accuracy on training set:',GradientBoost_Train_acc)
print('Accuracy on test set:',GradientBoost_Test_acc)

Accuracy on training set: 0.9454148471615721
Accuracy on test set: 0.9130434782608695


##**Using XGBoostClassifier**

In [ ]:
from xgboost import XGBClassifier
xgb_clf = XGBClassifier()
xgb_clf.fit(X_train1, y_train)

XGBClassifier()

In [ ]:
XGBoost_acc = xgb_clf.score(X_test1, y_test)
print(XGBoost_acc)

0.9304347826086956


In [ ]:
XGBoost_Train_acc= xgb_clf.score(X_train1,y_train)
XGBoost_Test_acc= xgb_clf.score(X_test1,y_test)
print('Accuracy on training set:',XGBoost_Train_acc)
print('Accuracy on test set:',XGBoost_Test_acc)

Accuracy on training set: 0.9847161572052402
Accuracy on test set: 0.9304347826086956


##**Using LightGBMClassifer**

In [ ]:
import lightgbm as lgb
model_lgb = lgb.LGBMClassifier()
# fit the model with the training data
model_lgb.fit(X_train1,y_train)

LGBMClassifier()

In [ ]:
predict_train = model_lgb.predict(X_train1)
# Accuray Score on train dataset
accuracy_train = accuracy_score(y_train,predict_train)
print('\naccuracy_score on train dataset : ', accuracy_train)


accuracy_score on train dataset :  1.0


In [ ]:
# predict the target on the test dataset
predict_test = model_lgb.predict(X_test1)
# Accuracy Score on test dataset
LightGBM_acc = accuracy_score(y_test,predict_test)
print('\naccuracy_score on test dataset : ', LightGBM_acc)


accuracy_score on test dataset :  0.9478260869565217


In [ ]:
LightGBM_Train_acc= model_lgb.score(X_train1,y_train)
LightGBM_Test_acc= model_lgb.score(X_test1,y_test)
print('Accuracy on training set:',LightGBM_Train_acc)
print('Accuracy on test set:',LightGBM_Test_acc)

Accuracy on training set: 1.0
Accuracy on test set: 0.9478260869565217


In [ ]:
y_pred = model_lgb.predict(X_test1)
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0])

In [ ]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[67  2]
 [ 4 42]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.96        69
           1       0.95      0.91      0.93        46

    accuracy                           0.95       115
   macro avg       0.95      0.94      0.95       115
weighted avg       0.95      0.95      0.95       115



In [ ]:
df1 = pd.DataFrame({
    'ML Algorithm': ['Logistic_Regression','Naive_Bayes','Random_Forest', 'Decicion_Tree', 'KNN', 'Kernalised SVM'],
    'Train_acc': [lr_clf_Train_acc, nb_clf_Train_acc, rf_clf_Train_acc, dec_clf_Train_acc, kNN_Train_acc, kernal_SVM_Train_acc],
    'Test_acc': [lr_clf_Test_acc, nb_clf_Test_acc, rf_clf_Test_acc, dec_clf_Test_acc, kNN_Test_acc, kernal_SVM_Test_acc],
    'Suitability': ['Not Suitable', 'Not Suitable', 'Not Suitable', 'Suitable', 'Not Suitable', 'Not Suitable']})
df1

ML Algorithm  Train_acc  Test_acc   Suitability
0  Logistic_Regression   0.825328  0.800000  Not Suitable
1          Naive_Bayes   0.816594  0.791304  Not Suitable
2        Random_Forest   0.944436  0.682246  Not Suitable
3        Decicion_Tree   1.000000  0.895652      Suitable
4                  KNN   0.882096  0.808696  Not Suitable
5       Kernalised SVM   0.801310  0.782609  Not Suitable

In [ ]:
 df1 = pd.DataFrame({
    'Boosting Algorithm': ['ADABoostClassifer','GradientBoostClassifer','XGBoostClassifer', 'LightGBMClassifier'],
 'Train_acc': [AdaBoost_Train_acc,GradientBoost_Train_acc,XGBoost_Train_acc,LightGBM_Train_acc],
    'Test_acc': [AdaBoost_Test_acc,GradientBoost_Test_acc,XGBoost_Test_acc,LightGBM_Test_acc],
    'Suitability': ['Not Suitable', 'Not Suitable', 'Not Suitable', 'Suitable']})
df1

Boosting Algorithm  Train_acc  Test_acc   Suitability
0       ADABoostClassifer   0.521834  0.400000  Not Suitable
1  GradientBoostClassifer   0.945415  0.913043  Not Suitable
2        XGBoostClassifer   0.984716  0.930435  Not Suitable
3      LightGBMClassifier   1.000000  0.947826      Suitable